development:
  adapter: postgresql
  encoding: unicode
  database: aggregator_<%= ENV['USER'] %>_dev
  # template: template0
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: "aggregator_<%= ENV['LOGNAME'] %>_test"
  template: template0
  pool: 5
